version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mealcatalog-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mealcatalog
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
